In [ ]:
# ----- SETUP (RUN ONCE) ------
# Before running make sure you set your fork
# You can find this from your forked repo under the code button
# Only run once, or if you CANNOT cd (change directory)
# into the repository
# For this to work (in colab)
# you must have created a GITHUB token
# and added it to colab.

from google.colab import userdata
email = userdata.get('GITHUB_USERNAME')
username = userdata.get('GITHUB_EMAIL')

# Change this to your forked url!!
gh_repo_url = "https://github.com/Savannah-Stuart10/fungal-temp-analysis.git"

# NOTE: set your email as your email
!git config --global user.email {email}

# NOTE: Change your username
!git config --global user.name {username}

# NOTE: change the address to the address of your fork!
!git clone {gh_repo_url}

fatal: destination path 'fungal-temp-analysis' already exists and is not an empty directory.

In [3]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [4]:
# make sure to run this cell to have access to this function below
def commit_and_push(repo_url, message):
    import os
    import subprocess
    from google.colab import userdata

    try:
        # change your username from mine to yours.
        username = userdata.get("GITHUB_USERNAME")
        token = userdata.get("GITHUB_TOKEN")
        !git add .
        !git commit -m "{message}"
        !git push "https://{username}:{token}@github.com/{username}/fungal-temp-analysis.git"
        print("Changes Saved to GitHub!")
    except Exception as e:
        print(e)

# Only call this function if you want to
def catch_up_to_main_repo():
    import os
    from google.colab import userdata
    try:
        username = userdata.get("GITHUB_USERNAME")
        token = userdata.get("GITHUB_TOKEN")
        main_repo = "https://github.com/nkmwicz/fungal-temp-analysis.git"
        !git remote add upstream {main_repo}
        !git fetch upstream
        !git merge upstream/main
        !git push https://{username}:{token}@github.com/{username}/fungal-temp-analysis.git
    except Exception as e:
        print(e)

In [5]:
!pip install ncbi-genome-download
!pip install pybarrnap

Requirement already satisfied: ncbi-genome-download in /usr/local/lib/python3.12/dist-packages (0.3.3)
Requirement already satisfied: appdirs in /usr/local/lib/python3.12/dist-packages (from ncbi-genome-download) (1.4.4)
Requirement already satisfied: requests>=2.4.3 in /usr/local/lib/python3.12/dist-packages (from ncbi-genome-download) (2.32.4)
Requirement already satisfied: tqdm in /usr/local/lib/python3.12/dist-packages (from ncbi-genome-download) (4.67.3)
Requirement already satisfied: charset_normalizer<4,>=2 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (3.4.4)
Requirement already satisfied: idna<4,>=2.5 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (3.11)
Requirement already satisfied: urllib3<3,>=1.21.1 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in /usr/local/lib/python3.12/dist-packages (from requests>=2.4.3->ncbi-genome-download) (2026.2.25)
Requirement already satisfied: pybarrnap in /usr/local/lib/python3.12/dist-packages (0.5.1)
Requirement already satisfied: biopython>=1.80 in /usr/local/lib/python3.12/dist-packages (from pybarrnap) (1.86)
Requirement already satisfied: pyhmmer>=0.11.0 in /usr/local/lib/python3.12/dist-packages (from pybarrnap) (0.11.0)
Requirement already satisfied: numpy in /usr/local/lib/python3.12/dist-packages (from biopython>=1.80->pybarrnap) (2.0.2)
Requirement already satisfied: psutil~=6.0 in /usr/local/lib/python3.12/dist-packages (from pyhmmer>=0.11.0->pybarrnap) (6.1.1)

In [ ]:
# SOME NOTES
# %ls shows the available files in the repo to get names of files
# to read a tsv, use pd.read_csv but pass in sep="\t"
# to reperesent tabs as separators

In [6]:
%cd fungal-temp-analysis
%ls

/content/fungal-temp-analysis
delete_me.csv                                   GCA_000002945.2.zip
eukaryotes_ncbi_temperatures.csv                LICENSE
FungiWork.ipynb                                 README.md
Fungi_Work_Working_File_While_Travelling.ipynb  temperature_data.tsv
GCA_000002945.2_dir/

In [7]:
import pandas as pd

eukaryotes_df = pd.read_csv("eukaryotes_ncbi_temperatures.csv")
eukaryotes_df.head()

,#Organism Name,Organism Groups,Strain,BioSample,BioProject,Assembly,Level,Size(Mb),GC%,Replicons,WGS,Scaffolds,CDS,Release Date,GenBank FTP,RefSeq FTP,Temperature (°C)
0,Neopyropia yezoensis,Eukaryota;Other;Other,NaN,SAMN13316713,PRJNA589917,GCA_009829735.1,Chromosome,107.591,64.8454,chromosome 1:CM020618.1; chromosome 2:CM020619...,WMLA01,28,0,2020-01-03T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/009...,NaN,NaN
1,Emiliania huxleyi CCMP1516,Eukaryota;Protists;Other Protists,CCMP1516,SAMN02744062,PRJNA77753,GCA_000372725.1,Scaffold,167.676,64.5000,NaN,AHAL01,7795,38554,2013-04-19T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000...,NaN
2,Glycine max,Eukaryota;Plants;Land Plants,NaN,SAMN00002965,PRJNA19861,GCA_000004515.5,Chromosome,978.942,35.1221,chromosome 1:NC_016088.4/CM000834.4; chromosom...,ACUP04,347,74248,2010-01-05T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000...,NaN
3,Medicago truncatula,Eukaryota;Plants;Land Plants,NaN,SAMN08400029,PRJNA702529,GCA_003473485.2,Chromosome,430.008,33.4462,chromosome 1:NC_053042.1/CM010648.1; chromosom...,PSQE01,42,42683,2018-09-06T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/003...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/003...,NaN
4,Solanum lycopersicum,Eukaryota;Plants;Land Plants,NaN,SAMN02981290,PRJNA119,GCA_000188115.3,Chromosome,828.349,35.6991,chromosome 1:NC_015438.3/CM001064.3; chromosom...,AEKE03,3150,37660,2010-12-10T00:00:00Z,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCA/000...,ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000...,NaN

In [8]:
#Isolate the needed columns for data filtering
needed_cols = ['#Organism Name', 'Organism Groups', 'Assembly', 'Temperature (°C)']

eukaryotes_df = eukaryotes_df[needed_cols]
eukaryotes_df.head()

,#Organism Name,Organism Groups,Assembly,Temperature (°C)
0,Neopyropia yezoensis,Eukaryota;Other;Other,GCA_009829735.1,NaN
1,Emiliania huxleyi CCMP1516,Eukaryota;Protists;Other Protists,GCA_000372725.1,NaN
2,Glycine max,Eukaryota;Plants;Land Plants,GCA_000004515.5,NaN
3,Medicago truncatula,Eukaryota;Plants;Land Plants,GCA_003473485.2,NaN
4,Solanum lycopersicum,Eukaryota;Plants;Land Plants,GCA_000188115.3,NaN

In [9]:
#drop all NAs in the temperature column so we are left with only known temperatures
eukaryotes_df = eukaryotes_df.dropna(subset = "Temperature (°C)")
eukaryotes_df.shape

(972, 4)

In [10]:
#filtering the new dataframe to only include fungal species in organism groups
eukaryotes_df = eukaryotes_df.loc[eukaryotes_df['Organism Groups'].str.contains("Fung")]
eukaryotes_df

,#Organism Name,Organism Groups,Assembly,Temperature (°C)
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0
...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0

In [11]:
#first attempt at dropping the duplicates in the assembly column. It was unsuccessful
eukaryotes_df.drop_duplicates(subset='Assembly')
eukaryotes_df

,#Organism Name,Organism Groups,Assembly,Temperature (°C)
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0
...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0

In [12]:
#use library re to make a column for species root name and get rid of any braces or other items in the name for duplicate purposes
import re
eukaryotes_df['species_root_name'] = eukaryotes_df['#Organism Name'].apply(lambda item: " ".join(item.split(" ")[:2]))
eukaryotes_df['species_root_name'] = eukaryotes_df['species_root_name'].apply(lambda item: re.sub(r"[\[\];'\",\(\).\-]", "", item))
eukaryotes_df

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0,Schizosaccharomyces pombe
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0,Aspergillus nidulans
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0,Aspergillus fumigatus
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0,Neurospora crassa
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0,Candida albicans
...,...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0,Hanseniaspora lindneri
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0,Cystobasidium slooffiae
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0,Candida anglica
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0,Penicillium brevicompactum
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0,Agaricus bisporus

In [13]:
#show the number of species root name that have unique values
len(eukaryotes_df['species_root_name'].unique())

946

In [14]:
#Assign a true or false to the species root name for future filtering
eukaryotes_df['duplicates'] = eukaryotes_df.duplicated(subset='species_root_name', keep=False)
eukaryotes_df

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name,duplicates
10,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0,Schizosaccharomyces pombe,False
11,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0,Aspergillus nidulans,False
12,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0,Aspergillus fumigatus,False
13,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0,Neurospora crassa,False
14,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0,Candida albicans,False
...,...,...,...,...,...,...
7874,Hanseniaspora lindneri,Eukaryota;Fungi;Ascomycetes,GCA_019649525.1,25.0,Hanseniaspora lindneri,False
7913,Cystobasidium slooffiae,Eukaryota;Fungi;Basidiomycetes,GCA_019775285.1,25.0,Cystobasidium slooffiae,False
7949,[Candida] anglica,Eukaryota;Fungi;Ascomycetes,GCA_019775655.1,25.0,Candida anglica,False
7961,Penicillium brevicompactum,Eukaryota;Fungi;Ascomycetes,GCA_019843585.1,24.0,Penicillium brevicompactum,False
8157,Agaricus bisporus var. bisporus H97,Eukaryota;Fungi;Basidiomycetes,GCA_000300575.1,24.0,Agaricus bisporus,False

In [ ]:
#Remove species that are uncertain
eukaryotes_df = eukaryotes_df.loc[~eukaryotes_df['#Organism Name'].str.contains(" cf. ")]
eukaryotes_df.shape

(954, 6)

In [15]:
eukaryotes_df = eukaryotes_df.reset_index(drop=True)
eukaryotes_df.head()

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name,duplicates
0,Schizosaccharomyces pombe,Eukaryota;Fungi;Ascomycetes,GCA_000002945.2,25.0,Schizosaccharomyces pombe,False
1,Aspergillus nidulans FGSC A4,Eukaryota;Fungi;Ascomycetes,GCA_000149205.2,26.0,Aspergillus nidulans,False
2,Aspergillus fumigatus Af293,Eukaryota;Fungi;Ascomycetes,GCA_000002655.1,28.0,Aspergillus fumigatus,False
3,Neurospora crassa OR74A,Eukaryota;Fungi;Ascomycetes,GCA_000182925.2,25.0,Neurospora crassa,False
4,Candida albicans SC5314,Eukaryota;Fungi;Ascomycetes,GCA_000182965.3,25.0,Candida albicans,False

In [ ]:
#Get fasta files
#unzip fasta
#run barrnap on fasta file for quality
#get tRNA and save it directly to the dataframe
#Changed tarfile to zipfile

import subprocess, zipfile, requests, os
from pybarrnap import Barrnap
from pybarrnap.utils import load_example_fasta_file

for row in range(1): # Change this range based on the number of rows you want to process
  assembly = eukaryotes_df.at[row, 'Assembly'] # Use the correct dataframe variable (df)
  url = f"https://api.ncbi.nlm.nih.gov/datasets/v2/genome/accession/{assembly}/download?include_annotation_type=GENOME_FASTA"
  res = requests.get(url)
  zip_filename = f'{assembly}.zip'
  with open(zip_filename, 'wb') as f:
      for chunk in res.iter_content(chunk_size=8192):
        f.write(chunk)
  print(f'Downloaded: {zip_filename}')
  extract_dir = f'{assembly}_dir'
  os.mkdir(extract_dir)

  with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
      zip_ref.extractall(extract_dir)

  %cd {extract_dir}/ncbi_dataset/data/{assembly}

  fasta_file = os.listdir()[0]
# Run pybarrnap rRNA prediction
  barrnap = Barrnap(
      fasta_file,
      evalue=1e-6,
      lencutoff=0.8,
      reject=0.25,
      threads=1,
      kingdom="bac", # Consider using "euk" for eukaryotes if appropriate
      accurate=False,
      quiet=False,
  )
  result = barrnap.run()
# Get rRNA features and print
  print("\n========== Print rRNA features ==========")
  for rec in result.seq_records:
    for feature in rec.features:
        if set(feature.qualfiers) & set(["5S_rRNA", "16S_rRNA", "23S_rRNA"]):
            print(feature.id, feature.type, feature.location, feature.qualifiers)
            # df.at[row, 'meets_criteria] = True
# Do something with the result

  print('Done Extracting')

# If you want to remove temporary files
# os.remove(zip_filename)
# shutil.rmtree(extract_dir)

  %cd../../../../
  %ls
  %rm ~rf {extrat_dir}

Downloaded: GCA_000002945.2.zip
/content/fungal-temp-analysis/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2

========== Print rRNA features ==========
CU329670.1 rRNA [149659:149774](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [456528:456643](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [912231:912346](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [1563476:1563591](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [2976820:2976935](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [3165397:3165512](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [3547901:3548016](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [3634372:3634487](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [3830381:3830496](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [3891664:3891779](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [4184356:4184471](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329670.1 rRNA [4240851:4240966](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [464528:464643](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [520304:520419](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [569152:569267](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [783260:783375](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [1199928:1200043](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [1406586:1406701](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [1504374:1504489](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [2032411:2032526](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [2261372:2261487](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [2322734:2322849](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [2442702:2442817](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [3096970:3097072](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [3171573:3171678](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [3938579:3938694](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [4161624:4161735](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329671.1 rRNA [4210382:4210497](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [38:502](-) {'gene': ['16S_rRNA'], 'product': ['16S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF00177'], 'note': ['aligned only 29.27 percent of the 16S ribosomal RNA']}
CU329672.1 rRNA [806:1347](-) {'gene': ['16S_rRNA'], 'product': ['16S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF00177'], 'note': ['aligned only 34.13 percent of the 16S ribosomal RNA']}
CU329672.1 rRNA [6308:7341](-) {'gene': ['23S_rRNA'], 'product': ['23S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF02541'], 'note': ['aligned only 31.96 percent of the 23S ribosomal RNA']}
CU329672.1 rRNA [7542:9542](-) {'gene': ['23S_rRNA'], 'product': ['23S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF02541'], 'note': ['aligned only 61.88 percent of the 23S ribosomal RNA']}
CU329672.1 rRNA [10421:11372](-) {'gene': ['16S_rRNA'], 'product': ['16S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF00177'], 'note': ['aligned only 60.00 percent of the 16S ribosomal RNA']}
CU329672.1 rRNA [11676:12217](-) {'gene': ['16S_rRNA'], 'product': ['16S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF00177'], 'note': ['aligned only 34.13 percent of the 16S ribosomal RNA']}
CU329672.1 rRNA [17178:18211](-) {'gene': ['23S_rRNA'], 'product': ['23S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF02541'], 'note': ['aligned only 31.96 percent of the 23S ribosomal RNA']}
CU329672.1 rRNA [18412:20412](-) {'gene': ['23S_rRNA'], 'product': ['23S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF02541'], 'note': ['aligned only 61.88 percent of the 23S ribosomal RNA']}
CU329672.1 rRNA [21291:22242](-) {'gene': ['16S_rRNA'], 'product': ['16S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF00177'], 'note': ['aligned only 60.00 percent of the 16S ribosomal RNA']}
CU329672.1 rRNA [22546:23087](-) {'gene': ['16S_rRNA'], 'product': ['16S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF00177'], 'note': ['aligned only 34.13 percent of the 16S ribosomal RNA']}
CU329672.1 rRNA [523318:523433](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [853315:853430](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [926143:926258](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [1370035:1370150](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [1474260:1474375](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [1690946:1691061](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [1702125:1702240](+) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [2308167:2308282](-) {'gene': ['5S_rRNA'], 'product': ['5S ribosomal RNA'], 'db_xref': ['RFAM:RF00001']}
CU329672.1 rRNA [2441036:2441577](+) {'gene': ['16S_rRNA'], 'product': ['16S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF00177'], 'note': ['aligned only 34.13 percent of the 16S ribosomal RNA']}
CU329672.1 rRNA [2441881:2442832](+) {'gene': ['16S_rRNA'], 'product': ['16S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF00177'], 'note': ['aligned only 60.00 percent of the 16S ribosomal RNA']}
CU329672.1 rRNA [2443711:2445711](+) {'gene': ['23S_rRNA'], 'product': ['23S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF02541'], 'note': ['aligned only 61.88 percent of the 23S ribosomal RNA']}
CU329672.1 rRNA [2445912:2446945](+) {'gene': ['23S_rRNA'], 'product': ['23S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF02541'], 'note': ['aligned only 31.96 percent of the 23S ribosomal RNA']}
CU329672.1 rRNA [2451925:2452466](+) {'gene': ['16S_rRNA'], 'product': ['16S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF00177'], 'note': ['aligned only 34.13 percent of the 16S ribosomal RNA']}
X54421.1 rRNA [212:1276](+) {'gene': ['23S_rRNA'], 'product': ['23S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF02541'], 'note': ['aligned only 32.92 percent of the 23S ribosomal RNA']}
X54421.1 rRNA [1416:2469](+) {'gene': ['23S_rRNA'], 'product': ['23S ribosomal RNA (partial)'], 'db_xref': ['RFAM:RF02541'], 'note': ['aligned only 32.58 percent of the 23S ribosomal RNA']}
X54421.1 rRNA [3146:4525](+) {'gene': ['16S_rRNA'], 'product': ['16S ribosomal RNA'], 'db_xref': ['RFAM:RF00177']}
Done Extracting

UsageError: Line magic function `%cd../../../../` not found.

In [16]:
#used pyhammr to solve dependencies between pybarnnap and pyhammr

print('Uninstalling current pyhmmer version...')
!pip uninstall -y pyhmmer

print('Installing pyhmmer version 0.11.0...')
!pip install pyhmmer==0.11.0

Uninstalling current pyhmmer version...
Found existing installation: pyhmmer 0.11.0
Uninstalling pyhmmer-0.11.0:
  Successfully uninstalled pyhmmer-0.11.0
Installing pyhmmer version 0.11.0...
Collecting pyhmmer==0.11.0
  Using cached pyhmmer-0.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl.metadata (15 kB)
Requirement already satisfied: psutil~=6.0 in /usr/local/lib/python3.12/dist-packages (from pyhmmer==0.11.0) (6.1.1)
Using cached pyhmmer-0.11.0-cp312-cp312-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (5.0 MB)
Installing collected packages: pyhmmer
Successfully installed pyhmmer-0.11.0

In [36]:
#Get fasta files
#unzip fasta
#run barrnap on fasta file for quality
#get tRNA and save it directly to the dataframe
#Changed tarfile to zipfile

from numpy import mean
import subprocess, zipfile, requests, os, shutil # Import shutil for rmtree
from pybarrnap import Barrnap
from pybarrnap.utils import load_example_fasta_file

for row in range(1): # Change this range based on the number of rows you want to process
  assembly = eukaryotes_df.at[row, 'Assembly'] # Use the correct dataframe variable (df)
  url = f"https://api.ncbi.nlm.nih.gov/datasets/v2/genome/accession/{assembly}/download?include_annotation_type=GENOME_FASTA"
  res = requests.get(url)
  zip_filename = f'{assembly}new.zip'
  with open(zip_filename, 'wb') as f:
      for chunk in res.iter_content(chunk_size=8192):
        f.write(chunk)
  print(f'Downloaded: {zip_filename}')
  extract_dir = f'{assembly}_dir'

  # Check if directory exists and remove it before creating
  if os.path.exists(extract_dir):
      shutil.rmtree(extract_dir)
  os.mkdir(extract_dir)

  with zipfile.ZipFile(zip_filename, 'r') as zip_ref:
      zip_ref.extractall(extract_dir)

  %cd {extract_dir}/ncbi_dataset/data/{assembly}

  fasta_file = os.listdir()[0]
# Run pybarrnap rRNA prediction
  barrnap = Barrnap(
      fasta_file,
      evalue=1e-6,
      lencutoff=0.8,
      reject=0.25,
      threads=1,
      kingdom="euk", # use "euk" for eukaryotes
      accurate=False,
      quiet=False,
  )
result = barrnap.run()
# Get rRNA features and print
gff_text = result.get_gff_text()
gff_text = [lines for lines in gff_text.split("\n")]
gff_mean = mean([
    float(item.split("/t")[5]) for item in gff_text[1:] if len(item.split("\t"))>5
    ])
print(gff_text)
print(gff_mean)

print("\n========== Print rRNA features ==========")
genes_set = set()
needed_genes = {"5S_rRNA", "5_8S_rRNA", "18S_rRNA", "28S_rRNA"} # Corrected 5.8S_rRNA to 5_8S_rRNA
e_value = []
for rec in result.seq_records: #first list
    print(rec)
    for feature in rec.features: #second list
        qualifiers = feature.qualifiers
        print(type(qualifiers))
        if "gene" in qualifiers:
            for g in qualifiers["gene"]:
              genes_set.add(g)

return_value = None
#if set(feature.qualfiers) & set(["18S_rRNA", "5.8S_rRNA", "28S_rRNA"]):
if all([any([needed in g for g in genes_set]) for needed in needed_genes]):
    return_value = True
else:
    return_value = False
print(return_value)


#print("It worked")
#print(f"gene_set : {genes_set}")
#print(f"needed_genes : {needed_genes}")


#meets_criteria = [evalue < 1e-6, lencutoff > 0.8, reject > 0.25]
#new_eukdf = eukaryotes_df + ['meets_criteria']

#for rec in result.seq_records:
 #if new_eukdf['meets_criteria'] = True
  #  set (new_eukdf.at[row, 'meets_criteria]) = True
   # for feature in rec.features:
    #if set(feature.qualifiers) & set(["5S_rRNA", "16S_rRNA", "23S_rRNA"]):
     #       print(feature.id, feature.type, feature.location, feature.qualifiers)


    #for feature in rec.features:
     #   if set(feature.qualfiers) & set(["5S_rRNA", "16S_rRNA", "23S_rRNA"]):
      #      print(feature.id, feature.type, feature.location, feature.qualifiers)
            # df.at[row, 'meets_criteria] = True
# Do something with the result

  #print('Done Extracting')

# If you want to remove temporary files
# os.remove(zip_filename)
# shutil.rmtree(extract_dir)

%cd ../../../..
%ls
%rm -rf {extract_dir}

Downloaded: GCA_000002945.2new.zip
/content/fungal-temp-analysis/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2/GCA_000002945.2_dir/ncbi_dataset/data/GCA_000002945.2

IndexError: list index out of range

In [ ]:
# Filter based on the presence of rRNA types
#this is where I am currently having issues filtering through
rRNA_criteria = ['18S_rRNA', '5.8S_rRNA', '28S_rRNA']
filtered_df = eukaryotes_df[eukaryotes_df['#Organism Name'].str.contains('|'.join(rRNA_criteria))]

display(filtered_df.head())
print(f"Shape of the filtered DataFrame: {filtered_df.shape}")

Empty DataFrame
Columns: [#Organism Name, Organism Groups, Assembly, Temperature (°C), species_root_name, duplicates]
Index: []

Shape of the filtered DataFrame: (0, 6)

In [ ]:
%cd ..

/content/fungal-temp-analysis/GCA_000002945.2_dir/ncbi_dataset
data/

In [ ]:
%rm -rf {extract_dir}

In [ ]:
#For those in species root name that are true for duplicate, print the duplicates
duplicated = eukaryotes_df.loc[eukaryotes_df['duplicates'] == True]
duplicated

,#Organism Name,Organism Groups,Assembly,Temperature (°C),species_root_name,duplicates
47,Cryptococcus neoformans var. neoformans JEC21,Eukaryota;Fungi;Basidiomycetes,GCA_000091045.1,27.0,Cryptococcus neoformans,True
1069,Saccharomyces cerevisiae x Saccharomyces kudri...,Eukaryota;Fungi;Ascomycetes,GCA_009665985.1,25.0,Saccharomyces cerevisiae,True
1495,Ogataea polymorpha,Eukaryota;Fungi;Ascomycetes,GCA_001664045.1,25.0,Ogataea polymorpha,True
1541,Saccharomyces cerevisiae x Saccharomyces uvarum,Eukaryota;Fungi;Ascomycetes,GCA_013180185.1,25.0,Saccharomyces cerevisiae,True
2300,Magnusiomyces capitatus NRRL Y-17686,Eukaryota;Fungi;Ascomycetes,GCA_900497725.1,25.0,Magnusiomyces capitatus,True
3227,Saccharomycopsis fibuligera,Eukaryota;Fungi;Ascomycetes,GCA_001936155.1,25.0,Saccharomycopsis fibuligera,True
4451,Magnusiomyces capitatus CNRMA 12.647,Eukaryota;Fungi;Ascomycetes,GCA_000817185.1,25.0,Magnusiomyces capitatus,True
4962,Cryptococcus neoformans AD hybrid,Eukaryota;Fungi;Basidiomycetes,GCA_006992865.1,27.0,Cryptococcus neoformans,True
5187,Saccharomyces cerevisiae x Saccharomyces eubay...,Eukaryota;Fungi;Ascomycetes,GCA_009665555.1,25.0,Saccharomyces cerevisiae,True
5188,Saccharomyces cerevisiae x Saccharomyces eubay...,Eukaryota;Fungi;Ascomycetes,GCA_009666275.1,25.0,Saccharomyces cerevisiae,True
5189,Saccharomyces cerevisiae x Saccharomyces eubay...,Eukaryota;Fungi;Ascomycetes,GCA_009667055.1,25.0,Saccharomyces cerevisiae,True
5190,Saccharomyces cerevisiae x Saccharomyces kudri...,Eukaryota;Fungi;Ascomycetes,GCA_009666465.1,25.0,Saccharomyces cerevisiae,True
5661,Saccharomyces cerevisiae x Saccharomyces kudri...,Eukaryota;Fungi;Ascomycetes,GCA_013180725.1,25.0,Saccharomyces cerevisiae,True
7812,Ogataea polymorpha x Ogataea parapolymorpha,Eukaryota;Fungi;Ascomycetes,GCA_019381815.1,25.0,Ogataea polymorpha,True

In [ ]:
# ----Keep as last cell----
# Use to save changes in repo that are not in this file.
# To save this file, use ctrl + s
# Then set commit message location, branch, etc.

# Change repo url to your forked url
url = "https://github.com/Savannah-Stuart10/fungal-temp-analysis.git"
# Change commit message
commit_and_push(url, "Added deleteme file for test")

[main 22de8bb] Added deleteme file for test
 1 file changed, 1 insertion(+)
Enumerating objects: 5, done.
Counting objects: 100% (5/5), done.
Delta compression using up to 2 threads
Compressing objects: 100% (3/3), done.
Writing objects: 100% (3/3), 328 bytes | 328.00 KiB/s, done.
Total 3 (delta 1), reused 0 (delta 0), pack-reused 0
remote: Resolving deltas: 100% (1/1), completed with 1 local object.
To https://github.com/Savannah-Stuart10/fungal-temp-analysis.git
   d052a69..22de8bb  main -> main
Changes Saved to GitHub!